// <auto-generated />
namespace Finances.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Ofx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ofx));
        
        string IMigrationMetadata.Id
        {
            get { return "201209291235474_Ofx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
