// <auto-generated />
namespace Finances.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ofxmoneytype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ofxmoneytype));
        
        string IMigrationMetadata.Id
        {
            get { return "201209291515365_ofxmoneytype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
