// <auto-generated />
namespace Finances.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class accounttransaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(accounttransaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201303121721254_account transaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
