// <auto-generated />
namespace Finances.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class transactionaccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transactionaccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201303011006391_transaction account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
