// <auto-generated />
namespace Finances.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class repeatprev : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(repeatprev));
        
        string IMigrationMetadata.Id
        {
            get { return "201303131637419_repeat prev"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
