var __cultureInfo = {
    "name": "fr-FR",
    "numberFormat": {
        "CurrencyDecimalDigits": 2,
        "CurrencyDecimalSeparator": ",",
        "CurrencyGroupSizes": [3],
        "NumberGroupSizes": [3],
        "PercentGroupSizes": [3],
        "CurrencyGroupSeparator": "Â ",
        "CurrencySymbol": "â‚¬",
        "NaNSymbol": "Non NumÃ©rique",
        "CurrencyNegativePattern": 8,
        "NumberNegativePattern": 1,
        "PercentPositivePattern": 0,
        "PercentNegativePattern": 0,
        "NegativeInfinitySymbol": "-Infini",
        "NegativeSign": "-",
        "NumberDecimalDigits": 2,
        "NumberDecimalSeparator": ",",
        "NumberGroupSeparator": "Â ",
        "CurrencyPositivePattern": 3,
        "PositiveInfinitySymbol": "+Infini",
        "PositiveSign": "+",
        "PercentDecimalDigits": 2,
        "PercentDecimalSeparator": ",",
        "PercentGroupSeparator": "Â ",
        "PercentSymbol": "%",
        "PerMilleSymbol": "â€°",
        "NativeDigits": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
        "DigitSubstitution": 1
    },
    "dateTimeFormat": {
        "AMDesignator": "",
        "Calendar": {
            "MinSupportedDateTime": new Date(-62135568000000),
            "MaxSupportedDateTime": new Date(253402300799999),
            "AlgorithmType": 1,
            "CalendarType": 1,
            "Eras": [1],
            "TwoDigitYearMax": 2029
        },
        "DateSeparator": "/",
        "FirstDayOfWeek": 1,
        "CalendarWeekRule": 0,
        "FullDateTimePattern": "dddd d MMMM yyyy HH:mm:ss",
        "LongDatePattern": "dddd d MMMM yyyy",
        "LongTimePattern": "HH:mm:ss",
        "MonthDayPattern": "d MMMM",
        "PMDesignator": "",
        "RFC1123Pattern": "ddd, dd MMM yyyy HH\u0027:\u0027mm\u0027:\u0027ss \u0027GMT\u0027",
        "ShortDatePattern": "dd/MM/yyyy",
        "ShortTimePattern": "HH:mm",
        "SortableDateTimePattern": "yyyy\u0027-\u0027MM\u0027-\u0027dd\u0027T\u0027HH\u0027:\u0027mm\u0027:\u0027ss",
        "TimeSeparator": ":",
        "UniversalSortableDateTimePattern": "yyyy\u0027-\u0027MM\u0027-\u0027dd HH\u0027:\u0027mm\u0027:\u0027ss\u0027Z\u0027",
        "YearMonthPattern": "MMMM yyyy",
        "AbbreviatedDayNames": ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."],
        "ShortestDayNames": ["di", "lu", "ma", "me", "je", "ve", "sa"],
        "DayNames": ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
        "AbbreviatedMonthNames": ["janv.", "fÃ©vr.", "mars", "avr.", "mai", "juin", "juil.", "aoÃ»t", "sept.", "oct.", "nov.", "dÃ©c.", ""],
        "MonthNames": ["janvier", "fÃ©vrier", "mars", "avril", "mai", "juin", "juillet", "aoÃ»t", "septembre", "octobre", "novembre", "dÃ©cembre", ""],
        "NativeCalendarName": "calendrier grÃ©gorien",
        "AbbreviatedMonthGenitiveNames": ["janv.", "fÃ©vr.", "mars", "avr.", "mai", "juin", "juil.", "aoÃ»t", "sept.", "oct.", "nov.", "dÃ©c.", ""],
        "MonthGenitiveNames": ["janvier", "fÃ©vrier", "mars", "avril", "mai", "juin", "juillet", "aoÃ»t", "septembre", "octobre", "novembre", "dÃ©cembre", ""]
    },
    "eras": [1, "ap. J.-C.", null, 0]
};